# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

force(true)
skip_binary_upload(true) # This will be done by fastlane beta